apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversao
  template:
    metadata:
      labels:
        app: conversao
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: conversao
        image: iadocicco/conversao-temperatura:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: conversao
  labels:
    app: conversao
spec:
  selector:
    app: conversao
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: NodePort
---
# Necessário ter objeto ServiceMonitor para poder monitorar via Prometheus
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: conversao
  labels:
    release: prometheus-grafana
spec:
  selector:
    matchLabels:
      app: conversao
  endpoints:
  - interval: 15s
    path: /metrics
    port: http
